<a href="https://colab.research.google.com/github/PIYUSH06VERMA/AI-foundations-ICG/blob/main/BCS_ASSN0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# **PART 1**

In [2]:
read_file='/content/sample_data/california_housing_train.csv'
df=pd.read_csv(read_file)

In [3]:
print(df.head(5))

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  


In [4]:
print(df.tail(10))

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.

In [5]:
print(df.describe())

          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.00000

In [6]:
unique=df['total_bedrooms'].unique()
print(unique)

[1283. 1901.  174. ... 1637. 1308.  936.]


In [7]:
total_bedrooms_per_total_rooms=df['total_bedrooms']/df['households']
df['total_bedrooms_per_total_rooms']=total_bedrooms_per_total_rooms
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  media

In [8]:
mn=df['total_bedrooms_per_total_rooms'].mean()
sd=df['total_bedrooms_per_total_rooms'].std()
print('mean is',mn)
print('Standard deviation is',sd)

mean is 1.0972809315785887
Standard deviation is 0.48905722079732394


In [9]:
print(df.loc[df['median_income']>5])

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  media

In [10]:
df2=df.loc[(df['total_rooms']>10000)&(df['median_house_value']<150000)]
print(df2)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  media

In [11]:
df.to_csv('modiefied.csv')

# **PART** **2**

In [12]:
import numpy as np

In [13]:
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [14]:
even_arr=arr[arr%2==0]
print(even_arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [15]:
d_arr=np.random.randint(10,100,size=(5,4))
print(d_arr)

[[94 85 15 51]
 [37 44 46 38]
 [16 69 29 93]
 [37 64 65 18]
 [66 38 40 71]]


In [16]:
sub=d_arr[0:3,0:2]
print(sub)

[[94 85]
 [37 44]
 [16 69]]


In [17]:
arr2=arr.reshape(4,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
arr2=arr2.ravel()
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [19]:
arr3=np.random.randint(1,100,size=(4,5))
print(d_arr.dot(arr3))

[[13522 13883 11712 14358 11220]
 [ 8985 10228  8464 10895  7654]
 [10234 15027 13412 15676  7720]
 [10406 10866  9700 12302  8755]
 [11448 13376  9978 13305 10057]]


In [20]:
new_arr=np.random.randint(0,100,size=(50))
print(new_arr)

[44 32  1 12 30 74 85  1 49 69 15 69 19 62 54 98 29 90 31 64 89 40 55 21
 32 20 34 38 22 92 76  4 69 43 67 57 99 61  7 73 66 61  8 19 48 56 22 71
 28 33]


In [21]:
sliced=new_arr[new_arr>50]
print(sliced)

[74 85 69 69 62 54 98 90 64 89 55 92 76 69 67 57 99 61 73 66 61 56 71]


In [22]:
index=[0,2,4,6,8,49]
fancy=new_arr[index]
print(fancy)

[44  1 30 85 49 33]


In [23]:
mn_arr=d_arr.mean(axis=0)
print(mn_arr)
mx_arr=d_arr.max(axis=0)
print(mx_arr)
sm_arr=d_arr.sum(axis=0)
print(sm_arr)

[50.  60.  39.  54.2]
[94 85 65 93]
[250 300 195 271]


In [24]:
mask=(d_arr>mn_arr)
filtered_arr=np.where(mask,d_arr,False)
print(filtered_arr)

[[94 85  0  0]
 [ 0  0 46  0]
 [ 0 69  0 93]
 [ 0 64 65  0]
 [66  0 40 71]]


# **PART 3**

In [25]:
zero=0
first=1
print(zero)
print(first)

while(True):
  result=zero+first
  if(result>100):
    break
  else:
    print(result)
    zero=first
    first=result

0
1
1
2
3
5
8
13
21
34
55
89


In [26]:
for i in range(1,51):
  if(i%3==0 and i%5==0):
    print('FizzBuzz')
  elif(i%3==0):
    print('Fizz')
  elif(i%5==0):
    print('Buzz')

Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz


In [27]:

user=input()
num=list(map(int,user.split()))
num.sort()
if (len(num)%2==0):
  print((num[len(num)//2-1]+num[len(num)//2])/2)
else:
  print(num[len(num)//2])

2 3 4 1 5
3


In [28]:
b=int(input())
a=1
try:
  print(a/b)
except:
  print('ERROR')

0
ERROR


# **PART 4**

In [29]:
arr_3d=np.random.randint(1,100,size=(2,3,4))
print(arr_3d)

[[[ 5 60 55 60]
  [ 4 44 36 51]
  [34 74 62 44]]

 [[44 43 17 64]
  [75 30 61 74]
  [55 50 70 51]]]


In [30]:
swapped=arr_3d.swapaxes(0,2)
print(swapped)

[[[ 5 44]
  [ 4 75]
  [34 55]]

 [[60 43]
  [44 30]
  [74 50]]

 [[55 17]
  [36 61]
  [62 70]]

 [[60 64]
  [51 74]
  [44 51]]]


In [31]:
summed=arr_3d.sum(axis=1)
print(summed)

[[ 43 178 153 155]
 [174 123 148 189]]


In [33]:
last_arr=np.random.randint(1,100,size=(5,5))
print(last_arr)
row_vec=np.array([1,2,3,4,5])
last_arr=last_arr+row_vec
print(last_arr)

[[64 10 36 11 93]
 [66 14 99 33 65]
 [88  6 22 79 69]
 [ 8 85 31  1 29]
 [61  4 58 62 20]]
[[ 65  12  39  15  98]
 [ 67  16 102  37  70]
 [ 89   8  25  83  74]
 [  9  87  34   5  34]
 [ 62   6  61  66  25]]
