Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [2]:
import numpy as np

In [3]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
python_list=[1,2,3,4,5]
array=np.array(python_list)
print(array)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
python_list=[[1,2,3],[4,5,6],[7,8,9]]
array=np.array(python_list)
print(array)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Write a NumPy function to create an array with random values of shape [3,4]
from numpy import random
def random_array():
    array=random.rand(3,4)
    return array
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
from numpy import random
def zero_array():
    array=random.choice([0],size=(3,4))
    return array

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
from numpy import random
def ones_array():
    array=random.choice([1],size=(3,4))
    return array


In [5]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
def range_array():
    array=np.arange(1,11,2)
    return array

### Basic array operations
- algebraic operations
- logical operations

In [6]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [22]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
import numpy as np
def arithmetic_operations(a,b):
    add=np.add(a,b)
    sub=np.subtract(a,b)
    mul=np.multiply(a,b)
    div=np.divide(a,b)
    return add,sub,mul,div

In [21]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
import numpy as np
def sum(a):
    x=np.sum(a,axis=0)
    return x

# Write a NumPy function to get the sum of the array 'a' along axis=1
import numpy as np
def sum(a):
    x=np.sum(a,axis=1)
    return x


In [20]:
# Write a NumPy function to reverse the array 'a'
import numpy as np
def reverse(a):
    x=a[::-1,::-1]
    return x

# Write a NumPy function to reverse the array 'a' along axis=0
import numpy as np
def reverse1(a):
    x=np.flip( a, axis=0)
    return x

# Write a NumPy function to reverse the array 'a' along axis=1
import numpy as np
def reverse2(a):
    x=np.flip(a, axis=1)
    return x

print(reverse(a))

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [19]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [18]:
# Write a NumPy function to sort the array 'a'
import numpy as np
def sort(a):
    x=np.sort(a)
    return x

# Write a NumPy function to sort the array 'a' along axis=0
import numpy as np
def sort(a):
    x=np.sort(a,axis=0)
    return x

# Write a NumPy function to sort the array 'a' along axis=1
import numpy as np
def sort(a):
    x=np.sort(a,axis=1)
    return x

# Write a NumPy function to sort the array 'a' in descending order along axis=0
import numpy as np
def sort(a):
    x=np.sort(a,axis=0)[::-1]
    return x


In [17]:
# Write a NumPy function to argsort the array along axis=0
import numpy as np
def argsort(a):
    x=np.argsort(a,axis=0)
    return x
# Write a NumPy function to argsort the array along axis=1
import numpy as np
def argsort(a):
    x=np.argsort(a,axis=1)
    return x


In [16]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
import numpy as np
def concatenate(a,b):
    x=np.concatenate((a,b))
    return x

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
import numpy as np
def concatenate(a,b):
    x=np.concatenate((a,b),axis=0)
    return x

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 1
import numpy as np
def concatenate(a,b):
    x=np.concatenate((a,b),axis=1)
    return x

# Note: You can do the same function using stacking, discover and try that :)
import numpy as np
def concatenate(a,b):
    x=np.vstack((a,b))#axis=0
    y=np.hstack((a,b))#axis=1
    return x,y


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [27]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [26]:
# Write a NumPy function to get the Number of dimensions
def ndim(a):
    x=np.ndim(a)
    return x

# Write a NumPy function to get the Shape of the array
def shape(a):
    x=np.shape(a)
    return x

# Write a NumPy function to get the Size of the array
def size(a):
    x=np.size(a)
    return x

In [28]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape(a):
    x=np.reshape(a,shape=(1,9))
    return x

In [29]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
def newaxis(a):
    x=np.reshape(a,shape=(1,3,3))
    y=np.array(a,ndmin=3)
    z=np.expand_dims(a,axis=0)
    return x,y,z



### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
def index_slice(a):
    x=a[0,0]
    y=a[(1,2)]
    z=a[1:2]
    return x,y,z


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
def condition(a):
    filterarr= a>4
    return a[filterarr]
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def condition(a):
    filterarr= (a>4) & (a%2==0)
    return a[filterarr]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [30]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def copy(a):
    x=np.copy(a)
    y=x+1
    return y

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [44]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd

data=pd.DataFrame(iris_2d)
print(data)
print(data.shape)
x=data.dropna()
print(x)
print(x.shape)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]
(150, 4)
       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]
(150, 4)


In [55]:
# Write a Pandas function to find the correlation between the first two columns.
print(data[1].corr(data[0]))

0         1         2         3
0  1.000000 -0.109369  0.871754  0.817954
1 -0.109369  1.000000 -0.420516 -0.356544
2  0.871754 -0.420516  1.000000  0.962757
3  0.817954 -0.356544  0.962757  1.000000

In [60]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
def stats(data):
    return data[2].mean(),data[2].median(),data[2].std()
print(stats(data))


(3.758666666666666, 4.35, 1.7644204199522617)


In [59]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
import math
data['Volume'] = (math.pi*data[2]*(data[0]**2))/3
print(data)


       0    1    2    3      Volume
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [68]:
from numpy import random
y=random.choice([1],size=(4,))
z=np.array(y,dtype=np.int64)
print(z)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [73]:
y = np.arange(1,10)
x = np.split(y, indices_or_sections=[4,6])
print(x)


[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [3]:
import numpy as np
from numpy import random
x=random.randint(10,size=(2,5))
print(x)
print(np.max(x,axis=1))
print(np.min(x,axis=1))
print([(i, np.where(x[i] == x.max(axis=1)[i])[0][0]) for i in range(2)])

[[9 4 8 3 0]
 [2 4 9 6 1]]
[9 9]
[0 1]
[(0, 0), (1, 2)]


### Pandas

Run the following load command and solve the following questions

In [85]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [86]:
data = pd.read_csv(url, names=names, header=None)
print(len(data['species'].unique()))

3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [87]:
bins = [0,3,5,99]
labels = ['small', 'medium', 'large']
size = np.array(pd.cut(data['petallength'], bins=bins, labels=labels))
print(size)

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'large' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'small' 'medium' 'large'
 'large' 'large' 'large' 'large' 'large' 'medium' 'large' 'large' 'large'
 'large' 'large' 'large' 'medium' 'large' 'large' 'large' 

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [4]:

print(data['petallength'].mode().squeeze())

NameError: name 'data' is not defined