Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

: 

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
x = np.empty(5)
for i in range(5):
  x[i]=i+1
print(x)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
x = np.zeros((3,3))
for i in range(3):
  for j in range(3):
    x[i][j]=i+j
print(x)

[1. 2. 3. 4. 5.]
[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
def random_arr():
  return np.random.rand(3,4)
print(random_arr())


# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
def zero_arr():
  return np.zeros((3,4))
print(zero_arr())


# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
def one_arr():
  return np.ones((3,4))
print(one_arr())

[[0.03771395 0.9484436  0.66795145 0.34977747]
 [0.84909463 0.64876162 0.98512417 0.51875334]
 [0.64990125 0.52905602 0.58498107 0.79800993]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
def evenspace(start, stop, number):
  return np.linspace(start, stop, number)
print(evenspace(1,5,10))


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
print(a)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]


In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def add(a,b):
  return np.add(a,b)
print(add(a,b))

def sub(a,b):
  return np.subtract(a,b)
print(sub(a,b))

#since there is division in question I will assume that array multiplication is not like matrix multiplication but rather element wise multiplication
def mul(a,b):
  return np.multiply(a,b)
print(mul(a,b))

def div(a,b):
  return np.divide(a,b)
print(div(a,b))

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [ ]:
#axis=0 means about column and axis=1 means along row
# Write a NumPy function to get the sum of the array 'a' along axis=0
def sum_axis0(a):
  return np.sum(a, axis=0)
print(sum_axis0(a))

# Write a NumPy function to get the sum of the array 'a' along axis=1
def sum_axis1(a):
  return np.sum(a,axis=1)
print(sum_axis1(a))

[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'
def reverse(a):
  return np.flip(a)
print(reverse(a))

# Write a NumPy function to reverse the array 'a' along axis=0
def reverse_axis0(a):
  return np.flip(a, axis=0)
print(reverse_axis0(a))

# Write a NumPy function to reverse the array 'a' along axis=1
def reverse_axis1(a):
  return np.flip(a, axis=1)
print(reverse_axis1(a))

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'

def sort(a):
  return np.sort(a)
print(sort(a))
# Write a NumPy function to sort the array 'a' along axis=0
def sort_axis0(a):
  return np.sort(a, axis=0)
print(sort_axis0(a))

# Write a NumPy function to sort the array 'a' along axis=1
def sort_axis1(a):
  return np.sort(a, axis=1)
print(sort_axis1(a))

# Write a NumPy function to sort the array 'a' in descending order along axis=0
def sortdesc(a):
  return np.sort(a)[::-1]
print(sortdesc(a))

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 1  5  8]
 [ 1  3  9]
 [-4  6  8]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0


# Write a NumPy function to argsort the array along axis=1


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concat(a,b):
  return np.concatenate((a,b), axis=0)
print(concat(a,b))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def concat_axis0(a,b):
  return np.concatenate((a,b),axis=0)
print(concat_axis0(a,b))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 1
def concat_axis1(a,b):
  return np.concatenate((a,b),axis=1)
print(concat_axis1(a,b))

# Note: You can do the same function using stacking, discover and try that :)


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
def dimension(a):
  return a.ndim
print(dimension(a))

# Write a NumPy function to get the Shape of the array
def shape(a):
  return a.shape #shape is in the form (row,column)
print(shape(a))

# Write a NumPy function to get the Size of the array
def size(a):
  return np.size(a)
print(size(a))

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape(a):
  return np.reshape(a,(1,9))
print(reshape(a))

[[-4  6  8  9  3  1  1  8  5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range

#will try later

1


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2

#will try later

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b = np.copy(a)
b=b+1
print(b)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3 ])
#print(iris_2d)
import pandas as pd
df = pd.DataFrame(iris_2d, columns=['sepal_length','sepal_width','petal_length','petal_width']) #converting numpy array into pandas dataframe
print(df)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
def drop(iris_2d):
  for i in iris_2d: #accessing a row in the iris_2d matrix
    if np.isnan(i) in i:
      np.delete(i)
  return iris_2d
print(drop(iris_2d))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
def correlation(df):
  print(df['sepal_length'].corr(df['sepal_width']))
correlation(df)

-0.10936924995064937


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
def stat(df):
  print(df['petal_length'].mean())
  print(df['petal_length'].median())
  print(df['petal_length'].std())
stat(df)

3.758666666666666
4.35
1.7644204199522617


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
def create_column(iris_2d):
  iris_2d = np.insert(iris_2d, 4, 1, axis=1) #filling the fourth column with value = 1
  return iris_2d
newdf = pd.DataFrame(create_column(iris_2d), columns=['sepal_length','sepal_width','petal_length','petal_width','volume'])

for index,row in newdf.iterrows():
  row['volume'] = np.pi * row['petal_length'] * (row['sepal_length']**2)/3
print(newdf)

     sepal_length  sepal_width  petal_length  petal_width      volume
0             5.1          3.5           1.4          0.2   38.132652
1             4.9          3.0           1.4          0.2   35.200498
2             4.7          3.2           1.3          0.2   30.072372
3             4.6          3.1           1.5          0.2   33.238050
4             5.0          3.6           1.4          0.2   36.651914
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3  244.445230
146           6.3          2.5           5.0          1.9  207.816354
147           6.5          3.0           5.2          2.0  230.069302
148           6.2          3.4           5.4          2.3  217.373079
149           5.9          3.0           5.1          1.8  185.910028

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
copy = np.ones(4,dtype=np.int64)
print(copy)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x = np.linspace(1, 9, 9, dtype=np.int64)
x1 = np.split(x, [4,6])
print(x1)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.randint(1,10, size=(2,5))
print(x)
print(np.max(x, axis=1)) #maximum value in column
print(np.min(x, axis=1)) #maximum value in column

[[2 4 6 8 5]
 [5 9 6 1 4]]
[8 9]
[2 1]


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
# will try later

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
def mode(df):
  print(df['petal_length'].mode())
mode(df)

0    1.5
Name: petal_length, dtype: float64
